app/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from app import db,login
from flask_login import UserMixin

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

user_role = db.Table('userRole',db.Column('user_id',db.Integer,db.ForeignKey('user.id')),
                     db.Column('role_id', db.Integer, db.ForeignKey('role.id')))
role_previlage = db.Table('rolePrevilage',db.Column('role_id',db.Integer,db.ForeignKey('role.id')),
                     db.Column('previlage', db.Integer, db.ForeignKey('previlage.id')))
class User(UserMixin,db.Model):
    """
    用户
    """
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64),index=True,unique=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(128),unique=True)
    sex = db.Column(db.String(10))
    #外键，可联合查询
    history = db.relationship('History',backref='author',lazy='dynamic')
    roles = db.relationship('Role',secondary=user_role,backref=db.backref('users',lazy='dynamic'),lazy='dynamic')
    def __repr__(self):#返回一个可以用来表示对象的可打印字符串
        return '<User {}>'.format(self.username)
    def set_password(self,password):
        self.password_hash = generate_password_hash(password=password)
    def check_password(self,password):
        return check_password_hash(self.password_hash,password)
    def check_email(self,email):
        return  not self.email == email
    def get_id(self):
        return self.id
class History(db.Model):
    """
    历史纪录
    """
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)
class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(140))
    previlages = db.relationship('Previlage',secondary=role_previlage,backref=db.backref('roles',lazy='dynamic'),lazy='dynamic')
    def __repr__(self):
        return '<Role {}>'.format(self.description)
    def getDescription(self):
        return self.description
class Previlage(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(140))

    def __repr__(self):
        return '<Previlage {}>'.format(self.description)

app/__init__.py
import logging
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from logging.handlers import RotatingFileHandler
from flask_session import Session
from flasgger import Swagger
from flask_cors import CORS
import os

db = SQLAlchemy() #表示数据库
migrate = Migrate() #数据库迁移引擎
login = LoginManager()
login.login_view = 'auth.login'
se = Session()
# login.login_message = ('Please log in to access this page.')

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    #插件关联
    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    se.init_app(app)
    Swagger(app)
    CORS(app)
    #注册蓝图
    from app.errors import bp as errors_bp
    from app.auth import bp as auth_bp
    from app.main import bp as main_bp
    from app.api import bp as api_bp
    from app.manage import bp as manage_bp
    app.register_blueprint(auth_bp,url_prefix='/auth')
    app.register_blueprint(errors_bp)
    app.register_blueprint(main_bp)
    app.register_blueprint(api_bp,url_prefix='/api')
    app.register_blueprint(manage_bp,url_prefix='/manage')
    if not app.debug:
        # ...

        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/end.log', maxBytes=10240,
                                           backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('end startup')

    return app
from app import models

app/api/__init__.py
# -*- coding:utf-8 -*-
"""
@author liuning
@date 2019/5/19 22:35
@File __init__.py.py 
@Desciption 接口
"""
import os

from flask import Blueprint

LOCAL_DIRECTORY_PATH = os.getcwd() + "/" #当前文件路径
bp = Blueprint('api',__name__)

from . import imgroutes,textroutes,apkroutes

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from flask_login import login_required

from app.main import bp

#主页
@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html')

@bp.route('/manage')
def manage():
    return  render_template('manage/index.html')

app/templates/base.html
<html>
    <head>
        {% if title %}
        <title>{{ title }} - microblog</title>
        {% else %}
        <title>microblog</title>
        {% endif %}
    </head>
    <body>
        <div>
            Microblog:
             <a href="{{ url_for('main.index') }}">Home</a>
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('auth.login') }}">Login</a>
            {% else %}
            <a href="{{ url_for('auth.logout') }}">Logout</a>
            {% endif %}
        </div>
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

app/templates/index.html
<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>移动应用鉴别系统</title><link href=/static/css/app.f2c8855e580b174ae0bb537fc12a5b89.css rel=stylesheet></head><body><div id=app></div><script type=text/javascript src=/static/js/manifest.2ae2e69a05c33dfc65f8.js></script><script type=text/javascript src=/static/js/vendor.02d2e9cc998f26f5c57a.js></script><script type=text/javascript src=/static/js/app.bc880dd03523c824142a.js></script></body></html>